MAX_ASSIGN_DISTANCE = 50
MIN_FRAME_APPEARANCE = 10
SLIDING_WINDOW_SIZE = 10
IMAGE_SIZE = 64
GREEN = (0, 255, 0)
RED = (0, 0, 255)
SMILE_MODEL_PATH = "state_dict_model_sensitivity.pt"
FRAMES_PER_SECOND = 24
